#Redis configuration, fill in redis details here. Redis is used for PUB/SUB only, so not many resources needed
redisHost: "123.4.5.6"
redisPort: "1234"
redisPassword: "password"

#Webhook config, for notifications when the plugin shuts down
webhookUrl: "https://discord.com/api/webhooks/1234/blabla"
#webhook message for warning on plugin shutdown (will not run on server shutdown)
webhookWarnMessage: "<@USERID> GameCoordinator has shut down!"